### ISSUE TITLE
Product detail: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#23]
### Overview

* **Page/Element:** Product detail page
* **URL:** `/<product-title>`
	
### Details

**Source files:**
* [Figma - Format desktop & mobile comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=728%3A25372)

**Tasks:**
* [ ] WP setup
  * NOTES ON SPEC FIELDS: 
     * The "Spec fields" as labeled in the data modeling sheet corresponding to [this table](https://user-images.githubusercontent.com/6934226/66756204-7eecc880-ee67-11e9-9604-3397d430cd79.png) on the front end.
     * Admins should be able to CRUD Spec FIelds. (Dave took a stab at the spec fields he knows of, but mentioned the client may have others they want to add.)
     * Spec fields should have a name field and an optional tooltip field

* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Products" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
* Directly above the footer, we should add a "related products" component. My gut is that this should be coded into the template vs. a flexible page block, since they want to use a unique pattern. 
* Note that mobile comp may not reflect design revisions based on client feedback. Refer to the desktop comp for final patterns/design and use mobile comp just as a guide for how things should stack responsively.

**D. Comps**
![ProductDetail_Desktop](https://user-images.githubusercontent.com/54903335/67334357-01245f00-f4f0-11e9-83a2-493937c2bc31.jpg)

![ProductDetail_Mobile](https://user-images.githubusercontent.com/54903335/67334464-2f09a380-f4f0-11e9-8835-2a819105eddf.png)

**Comment by gracecanfield** [comment]
@lindsayholloway Sample product page for testing: https://npm.staging.vigetx.com/product/mid-roll/

**Comment by gracecanfield** [comment]
**QA fixes needed:**
* [ ] Update cards to be no-image cards (latest style in comps)
* [ ] Add functionality to include Work Cards (latest style in comps)
* [ ] Formatting doesn’t change when Overview Media is removed (latest style in comps)
* [ ] If only an image is uploaded and no video, nothing shows up 
* [ ] Specs > no video links work
* [ ] Specs >  if a video is uploaded with no image, nothing shows up
* [ ] Specs > More than 7 spec groups can be added (should be limited to 7, ideally)
