### ISSUE TITLE
Work detail: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#30]
### Overview

* **Page/Element:** Work detail
* **URL:** `/<work-title>`
	
### Details

**Source files:**
* [Figma - Batch 2 - Work desktop comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=728%3A25372)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Work" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
N/A

**D. Comps**

![Work Detail (Case Study)](https://user-images.githubusercontent.com/6934226/67317441-0ecdea80-f4d8-11e9-8ad3-364eef15de14.jpg)

**Comment by gracecanfield** [comment]
[Staging admin example page](https://live-national-public-media-v2.pantheonsite.io/wp/wp-admin/post.php?post=16&action=edit)
[Staging front-end example page](https://live-national-public-media-v2.pantheonsite.io/work/16/)

**High Priority (before client demo):**
* [ ] Cross-reference the comp and clean up this page, please. The styling on this page is extremely rough. (Hero image isn’t displaying, No padding in the hero text, no padding between the work groups). 
* [ ] We need to have access to [all of these page blocks](https://airtable.com/tbljc70sgRwYWsS7k/viwcPzoIGM97kqc1V?blocks=hide) on this page. 
**Medium Priority:**
* [ ] In the audio work groups, in the comp there’s a place to show a related program. We’re not doing that on the front-end. ([comp screenshot](https://www.dropbox.com/s/5avje67ec9423tv/Screenshot%202019-10-31%2014.59.31.png?dl=0), 
* [ ] Three different hero image variations should be possible (Phone, Laptop, Tablet) - Only one is available in the CMS.
* [ ] Work group: Image type: There is one text field for each group, but there should additionally be individual text fields for each image gallery item (acting as a caption for each image.)
* [ ] What is the difference between the first Image field in the main body area; and the Featured Image and Image fields in the right column? If we need to have both, can we rename the fields on the right to “Related Work image”, “Related Work Video”?
* [ ] URL structure uses a number in the slug instead of the work title. - https://live-national-public-media-v2.pantheonsite.io/work/16/ instead of /work/<work-title>
* [ ] How tough would it be to rename the “Work” block to “Related Work”? (If it’s a pain, don’t worry about it.)

**Comment by justinvandenberg** [comment]
@gracecanfield 
* There's a thumbnail field for the audio work. I can switch it to a post object field. Would we ever want a different image than the program one? 
* The image field should be able to handle all of the phone, tablet, laptop images. 
* The caption gets pulled through from the image's caption. 
* All the fields on the side are for when the post gets pulled in somewhere else. The main column is for the detail page.
* URL structure gets set on the initial publish. I'm guessing that one got published without a title, all the other posts look right.

**Comment by gracecanfield** [comment]
**Additional high priority QA fix needed:**
https://live-national-public-media-v2.pantheonsite.io/work/16/
* [ ] Work Groups block: Video isn't showing a thumbnail. Not sure if this is because an image wasn't uploaded, but if no image is uploaded we should default to the regular video thumbnail.
* **Work block regressions:**
  * The video thumbnail isn't playing the video when you click the play button.
  * "View the work" isn't linking to the detail page.
  * Work titles aren't displaying

**Comment by gracecanfield** [comment]
Work groups block: Needs an image because audio player isn't embedded (appears in a modal).
