### ISSUE TITLE
Insights index: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#32]
### Overview

* **Page/Element:** Insights index page
* **URL:** `/insights`
	
### Details

**Source files:**
* [Figma - Batch 4 - Insights index desktop & mobile comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=1745%3A29566)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Insights index" and "Articles" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
* None! (everything should be reflected in zee comps)

**D. Comps**

![Insights Index - Image](https://user-images.githubusercontent.com/6934226/67332690-6296fe80-f4ed-11e9-847f-160fa620c29f.jpg)

![Insights Index - Video](https://user-images.githubusercontent.com/6934226/67332707-688cdf80-f4ed-11e9-8f7f-8c027cb14058.png)

**Comment by justinvandenberg** [comment]
@gracecanfield should I make Reports a new post type? I think that would make sense.

**Comment by gracecanfield** [comment]
@justinvandenberg I agree that that would make sense!

**Comment by justinvandenberg** [comment]
@gracecanfield I've created a page for this on staging. The Reports/Insights will have to be populated as well.

**Comment by gracecanfield** [comment]
[Staging link](https://live-national-public-media-v2.pantheonsite.io/insights/)

**High Priority:**
* [ ] All insights aren’t displaying in reverse-chron order beneath the blocks ([comp screenshot of desired](https://www.dropbox.com/s/dvj82fsxk72krey/Screenshot%202019-10-31%2017.23.36.png?dl=0)). Note that 6 should display (both Insights and Reports), and then a load more button where a user can load more insights. 
* [ ] “featured insight” and “featured report” - On each, if the “Button text” and “Button link” fields aren’t filled out, we should have the button text say “Read more” and link to the detail page by default. We should never hit a scenario where an empty button displays.

**Low Priority:**
* [ ] If there is no featured report block, a blue section that’s blank but just has the word “Insights” displays. This shouldn’t display. ([screenshot](https://www.dropbox.com/s/5rne4lnic2vk7r6/Screenshot%202019-10-31%2017.10.01.png?dl=0))

**Comment by gracecanfield** [comment]
@justinvandenberg Just wanted to flag that I added an additional low-priority visual QA item in the bulleted list above.

**Comment by gracecanfield** [comment]
Just a note - the "load more" function still isn't working (I see that hasn't been checked off, but since the other QA fixes appear to have been completed, I wanted to flag.)

**Comment by justinvandenberg** [comment]
@gracecanfield I have the load more set to 9 right now. I can change that once I get a second.
