### ISSUE TITLE
About: Build-out & WP config

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#33]
### Overview

* **Page/Element:** About page
* **URL:** `/about`
	
### Details

**Source files:**
* [Figma - Batch 4 - About comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=1745%3A29566)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "About" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
* None! (everything should be reflected in zee comps)

**D. Comps**

![About](https://user-images.githubusercontent.com/6934226/67332626-48f5b700-f4ed-11e9-8b6d-3d759c6acc78.jpg)

**Comment by gracecanfield** [comment]
[Staging link](https://live-national-public-media-v2.pantheonsite.io/about/)

**High Priority:**
* [ ] Within the “Locations” block, there doesn’t seem to be a place to add actual offices that appear in the comp. ([comp screenshot](https://www.dropbox.com/s/5vctf15mrocfuuv/Screenshot%202019-10-31%2015.51.52.png?dl=0))

**Low Priority:**
* [ ] There should be a little carrot icon to show users they can expand to see bio ([comp screenshot](https://www.dropbox.com/s/c4xs6cekvzpx28g/Screenshot%202019-10-31%2015.54.00.png?dl=0))
* [ ] Insights are supposed to be pulled in directly into the About page (this was in the annotations/airtable). Insights should have a lightswitch where admins can select that a given Insight should appear on the About page but not the Insights index. If that lightswitch is selected, the Insight should hide from the index page but instead automatically pull into the About page. We can keep the insights fields in the About page, but they can act as an override if admins want to override the insights that automatically display.

**Comment by justinvandenberg** [comment]
@gracecanfield I moved the locations to the Globals tab, I think I mentioned it yesterday.

**Comment by gracecanfield** [comment]
@justinvandenberg Sorry! You told me that. 🤦‍♀ Thanks!
