### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#4]
**Tasks:**

* [x] Craft data setup
* [x] Build tools setup
* [ ] Hook up Pantheon CDN (if needed?)
* [x] CSS system setup
* [ ] Get deploys running
