### ISSUE TITLE
Header: WP setup & build-out

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#6]
### Overview

* **Page/Element:** Header 
	
### Details

**Source files:**
[Figma - master components](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---Round-2?node-id=1%3A177)

**Tasks:**
* [x] Admins should be able to edit header navigation items
  * Primary link text & corresponding entry/URL
  * Some way of flagging if an item had secondary links (if it does, we would show the dropdown)
  * For each secondary link, letting admins fill in a title (required), description (optional), icon (optional) and up to three tertiary text + links (to accommodate the "Podcasts, Radio, Voice" links under Audio)
* [x] Build-out & wire-up header

**Functional specifications:**
* Note that "Platforms" has a dropdown menu, but none of the other links do. Happy to talk through CMS approach for this if it's helpful.

**Screenshots:**

<img width="748" alt="Screen Shot 2019-09-23 at 3 54 31 PM" src="https://user-images.githubusercontent.com/6934226/65457851-77af3d80-de1a-11e9-910c-1dfe0815afc0.png">

<img width="756" alt="Screen Shot 2019-09-23 at 3 53 42 PM" src="https://user-images.githubusercontent.com/6934226/65457801-6108e680-de1a-11e9-95b9-e790656a0115.png">

**Comment by gracecanfield** [comment]
@justinvandenberg I realize this is still in Code Review, but wanted to flag a QA fix needed:

* [ ] Header text should be vertically center-aligned.

![](https://www.dropbox.com/s/zwxinhdop9556eq/Screenshot%202019-10-15%2010.53.02.png?dl=0)

**Comment by gracecanfield** [comment]
@justinvandenberg Consolidated list of QA fixes for the header:

Admin:
* [ ] Admins should be able to add an icon to Formats (displays both in the header Platforms dropdown and in the format filters on product index page, plus on product cards).
* [ ] Admins should be able to add a Short Description to Formats that displays in the header dropdown ([comp screenshot](https://www.dropbox.com/s/hii28w805s2gdwh/Screenshot%202019-10-18%2009.00.01.png?dl=0)

Front-end:
* [ ] Header text should be vertically center-aligned ([screenshot](https://www.dropbox.com/s/zwxinhdop9556eq/Screenshot%202019-10-15%2010.53.02.png?dl=0))
