### ISSUE TITLE
Audiences page: WP setup & build-out

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#7]
### Overview

* **Page/Element:** Audiences page
* **URL:** `/<audiences>`
	
### Details

**Source files:**
* [Figma - Format desktop & mobile comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=418%3A11916)

**Tasks:**
* [ ] WP setup
* [ ] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Audiences" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma (linked above)

**C. Revisions in build**
* Note that the image beneath the Results section needs to be replaced by Mindy—it's possible it might be more of a background image effect when she replaces, so let's hold off on building this section.

**D. Comps**

![Audience Index](https://user-images.githubusercontent.com/6934226/66487630-a95f1000-ea7a-11e9-89fa-bc166ea411bd.png)

![Audience - Accordion Open](https://user-images.githubusercontent.com/6934226/66487617-9fd5a800-ea7a-11e9-907e-3134ea023587.png)

**Comment by gracecanfield** [comment]
@justinvandenberg This ticket has been updated with deets!

**Comment by gracecanfield** [comment]
@lindsayholloway Staging link for testing: https://npm.staging.vigetx.com/audience/

**Comment by gracecanfield** [comment]
**QA fixes needed:**
* [ ] There should be an attribution field that can display at the bottom of the audiences block (for each “audience” block/carousel item).(see [comp screenshot](https://www.dropbox.com/s/ka9bc2w7am8leqa/Screenshot%202019-10-18%2012.38.24.png?dl=0))
* [ ] Audiences carousel: Stats aren’t displaying on the front-end even if entered in the admin.
* [ ] Audience block > You can currently enter in more than 3 stats, though the front-end only accommodates 3 stats (if this is annoying to change for this one template, don't worry about it.)
* [ ] the placement of the audience names “cultured, tech savvy” etc changes for each one you click on https://npm.staging.vigetx.com/audience/
* [ ] Photo background treatment
* [ ] For the stat block, there should be a gray background option (see master components in Figma)
