### ISSUE TITLE
Format page: WP setup & build-out

### ISSUE THREAD

**Issue by gracecanfield** [vigetlabs/npm#8]
### Overview

* **Page/Element:** Format page
* **URL:** `/<format-title>`
	
### Details

**Source files:**
* [Figma - Format desktop & mobile comp](https://www.figma.com/file/NmTYeQFyu7XPlzTMSKFOzF/NPM-Comps---For-Buildout?node-id=418%3A11916)

**Tasks:**
* [] WP setup
* [] Build-out & wire-up

**Functional specifications:**

**A. CMS fields**
See "Format" section of [data modeling airtable - Content Types & Fields tab](https://airtable.com/tblYGOMZcUp2WYox2/viwqDJ7kPQqzVkGKN?blocks=hide)

**B. Annotations**
See annotations and comments in Figma

**C. Revisions**
NOTE that there is one outstanding revision to make the [secondary CTAs](https://www.dropbox.com/s/vyznu9w28ltrpgt/Screenshot%202019-10-08%2009.00.34.png?dl=0) more card-like in design.

**D. Comps**

![Format - 3 Primary (Audio)](https://user-images.githubusercontent.com/6934226/66412316-465e7200-e9c3-11e9-8365-c5ac128d22d7.png)

![Audio Format](https://user-images.githubusercontent.com/6934226/66412332-4c545300-e9c3-11e9-8a4d-96c57980e9d7.png)

**Comment by gracecanfield** [comment]
@justinvandenberg Details added to the ticket!

**Comment by gracecanfield** [comment]
@justinvandenberg 

**QA Fixes:**

* [ ] Hero image should be taller and overlap blue bar
* [ ] “Our Results” should be blue
* [ ] Stat description text appears to be the wrong font style (at least, it shouldn’t be italic).
Lower priority:
* [ ] There should be a thin gray dividing line between header & page body
* [ ] “NPR Audio” label - “Audio” should be Title Case, not all caps

Screenshot of comp on the left, staging on the right:
https://www.dropbox.com/s/i05xipmyvnmj5so/Screenshot%202019-10-14%2015.16.23.png?dl=0
